sudo: false
language: ruby
rvm: 2.2.0
install:
- bundle install --without production --deployment
- npm install
cache:
  directories:
  - vendor/bundle
  - node_modules
script:
- node test/category-checker.js
- bundle exec rake deploy
env:
  global:
    secure: cIhEBITJHfD+S4KRmefZr7tCZui0Kc3OI+jvSQ8g6X97nqRktucex1fk1hLmVmAx59wJ6QiwJLHHvsNzL49nn0dNQsnIcaw4Y+W7jCkmeHLay7/IZRBtl2W8zOpb51n7eNwNOcQDB3h57788xqF2HtwmDnKHjtPda/9uRnFWuzk=
branches:
  except:
  - master
