sudo: false
language: ruby
rvm: 2.2.0
install:
- bundle install --without production --deployment
cache:
  directories:
  - vendor/bundle
script: bundle exec rake deploy
env:
  global:
  - secure: ObLqnvaWmZ7JDSyY2ckqhPFa3rroUZE9l1L+UOIOZ2tYT+FtydE84461aju/E4OSJN8XIXtUVELX1E2EiwI2GDDaaT9fophhFAOfcF+0KjLjCALwmELAtcfhWDQw6X0d7O5i6UdakorBblhvsdrmurzIMVTvw4bqywB/ktAAQDs=
  - secure: XaFTmiD4u59xW7JCe8f+1dYAsnD9+HY1VtfwuzjivUv21yzjGhClcigDlroi0v1n+VAt6NBPLC6qv2gjA4CkHBaKqrTvGhhgRCvNIhN9g8xPMCGNL4pLXv6G3xraDaH7cLHtxwvVv51ZGHm/Aw14aCQ2jJ0V+4GUrWhuxZK8G4M=
branches:
  except:
    - master