sudo: false
language: node_js
install:
- npm install
- bundle install
before_script: "./test/travis-spellcheck.sh"
script: bundle exec jekyll build
env:
  global:
    secure: ObLqnvaWmZ7JDSyY2ckqhPFa3rroUZE9l1L+UOIOZ2tYT+FtydE84461aju/E4OSJN8XIXtUVELX1E2EiwI2GDDaaT9fophhFAOfcF+0KjLjCALwmELAtcfhWDQw6X0d7O5i6UdakorBblhvsdrmurzIMVTvw4bqywB/ktAAQDs=
