# Site settings
title: JSer.info
email: info@efcl.info
description: "世界のJavaScriptを紹介するサイト"
keywords:
  - "JavaScript"
  - "ブラウザ"
  - "ECMAScript"
url: "http://jser.info"
baseurl: ""
production_url : "http://jser.info"
github_repo_url : https://github.com/jser/jser.github.io
timezone: Asia/Tokyo
encoding: utf-8
exclude: ["README.md"]
# Setup
author:
  name: 'azu'
  url:  http://jser.info/
  twitter: azu_re
  github:  azu

paginate: 10
paginate_path: "page/:num"
permalink: /:year/:month/:day/:title/
# Github equal
safe: true
lsi: false
# Build settings
markdown: kramdown

kramdown:
  auto_ids: true


gems:
  - jekyll-sitemap
# Prose
prose:
  rooturl: '_posts/'
  siteurl: 'http://jser.info'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "hidden"
          label: "Author"
          value: "azu"
          placeholder: "Trunk Botterson"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Post Tag"
          placeholder: "Create or choose"
          alterable: true
